apps/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
]

apps/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("list/", views.ContactsListView.as_view(), name="contacts_list"),
    path("create/", views.ContactsCreateView.as_view(), name="contacts_create"),
    path("update/<int:pk>/", views.ContactsUpdateView.as_view(), name="contacts_update"),
    path("delete/<int:pk>/", views.ContactsDeleteView.as_view(), name="contacts_delete"),
    path("generate/", views.generate_contacts_view, name="contacts_generate"),
    path("delete/", views.delete_contacts_view, name="contacts_delete"),
]

apps/homework11/urls.py
from django.urls import path, include

from apps.homework11 import views

app_name = "homework11"

urlpatterns = [
    path(
        "generate-humans/",
        include(
            [
                path("<int:amount>/", views.generate_humans_view, name="generate_humans_with_amount"),
                path("", views.generate_humans_view, name="generate_humans"),
            ]
        ),
    ),
]

apps/homework_11/urls.py
from django.urls import path, include

from apps.homework_11 import views

app_name = "homework_11"

urlpatterns = [
    path(
        "generate-humans/",
        include(
            [
                path("<int:amount>/", views.generate_humans_view, name="generate_humans_with_amount"),
                path("", views.generate_humans_view, name="generate_humans"),
            ]
        ),
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.base.urls")),
    path("first-example/", include("apps.homework11.urls")),
    path("contacts/", include("apps.contacts.urls")),
]

apps/contacts/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=21)

    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return f"{self.name}"

apps/contacts/models/contact.py
from django.db import models

from .group import Group


class Contact(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.CharField(max_length=15, null=True, blank=True)

    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
    )

    groups = models.ManyToManyField(
        Group,
        related_name="animals",
    )

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        ordering = ["-modified_at", "name"]

apps/contacts/models/group.py
from django.db import models


class Group(models.Model):
    """
    Color of animal.
    For example:
        - Family
        - Work
        - Friend
        -Travel
        - etc.
    """

    value = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.value = self.value.capitalize()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.value

    __repr__ = __str__

apps/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

apps/contacts/forms.py
from django import forms


class GenerateForm(forms.Form):
    amount = forms.IntegerField(
        label="Amount",
        min_value=1,
        max_value=100,
        required=True,
        initial=10,
    )

apps/base/views.py
from django.shortcuts import render


def index(request):
    return render(
        request=request,
        template_name="base/home_page.html",
        context={
            "greetings_text": " Hello! ",
            "title": "Home page",
        },
    )

apps/contacts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from apps.contacts.forms import GenerateForm
from apps.contacts.models import Contact
from apps.contacts.services.delete_contacts import delete_contacts
from apps.contacts.services.generate_and_save_contacts import generate_and_save_contacts


class ContactsListView(ListView):
    model = Contact


class ContactsCreateView(CreateView):
    model = Contact
    fields = ("name", "birthday")
    success_url = reverse_lazy("contacts:contacts_list")


class ContactsUpdateView(UpdateView):
    model = Contact
    fields = ("name", "birthday")
    success_url = reverse_lazy("contacts:contacts_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


class ContactsDeleteView(DeleteView):
    model = Contact
    success_url = reverse_lazy("contacts:contacts_list")


def generate_contacts_view__raw_form(request):
    if request.method == "POST":
        amount = int(request.POST["amount"])

        generate_and_save_contacts(amount=amount)

    return render(
        request=request,
        template_name="contacts/contact_generate.html",
        context=dict(
            contacts_list=Contact.objects.all(),
        ),
    )


def generate_contacts_view(request):
    if request.method == "POST":
        form = GenerateForm(request.POST)

        if form.is_valid():
            amount = form.cleaned_data["amount"]

            generate_and_save_contacts(amount=amount)
    else:
        form = GenerateForm

    return render(
        request=request,
        template_name="contacts/contact_generate.html",
        context=dict(
            contacts_list=Contact.objects.all(),
            form=form,
        ),
    )


def delete_contacts_view(request):
    delete_contacts()

    return redirect(reverse_lazy("contacts:contacts_list"))

apps/homework11/views/generate_humans.py
from django.shortcuts import render

from apps.homework11.services.generate_humans import generate_humans


def generate_humans_view(
        request,
        amount: int = 10,
):
    humans = generate_humans(amount=amount)

    return render(
        request=request,
        template_name="homework_11/generate_humans.html",
        context=dict(
            humans=humans,
        ),
    )

apps/homework_11/views/generate_humans.py
from django.shortcuts import render

from apps.homework_11.services.generate_humans import generate_humans


def generate_humans_view(
        request,
        amount: int = 10,
):
    humans = generate_humans(amount=amount)

    return render(
        request=request,
        template_name="homework_11/generate_humans.html",
        context=dict(
            humans=humans,
        ),
    )

apps/templates/_helpers/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% else %}
                Welcome!
            {% endif %}
            | My Website
        {% endblock %}
    </title>
</head>
<body>
{% include "_helpers/_header.html" %}

<div>
    {% block content %}
        <h1>Welcome!</h1>
    {% endblock %}
</div>

</body>
</html>

apps/templates/_helpers/_header.html
<header>
    <div>Logo</div>


    <ul>
        <li>
            <a href="{% url 'base:index' %}">
                Home
            </a>
        </li>
        <li>
            <a href="{% url 'homework11:generate_humans' %}">
                Generate humans
            </a>
        </li>
        <li>
            <a href="{% url 'contacts:contacts_list' %}">
                Contact
            </a>
        </li>
        <li>
            <a href="{% url 'admin:index' %}">
                Admin
            </a>
        </li>
    </ul>
</header>

apps/templates/base/home_page.html
{% extends "_helpers/_base.html" %}


{% block title %}
    {{ title }} :)
{% endblock %}


{% block content %}
    <p>{{ greetings_text }}</p>
{% endblock %}

apps/templates/contacts/_contact_list_base.html
<div>
    <a href="{% url 'contacts:contacts_create' %}">
        <button>Create</button>
    </a>
    <a href="{% url 'contacts:contacts_generate' %}">
        <button>Generate new contacts</button>
    </a>
    <a href="{% url 'contacts:contacts_delete' %}">
        <button>Delete contacts</button>
    </a>
</div>

<ol>
    {% for contact in contacts_list %}
        <li>
            <div style="display: flex; flex-flow: row;">
                <div style="margin: .2em;">
                    <span>{{ contact.name }}</span>
                    <span> - </span>
                    <span>{{ contact.birthday }}</span>
                    <span> - </span>
                    <span>{{ contact.modified_at }}</span>
                </div>
                <div style="margin: .2em">
                    <a href="{% url 'contacts:contacts_update' contact.pk %}">
                        <button>Update</button>
                    </a>
                    <a href="{% url 'contacts:contacts_delete' contact.pk %}">
                        <button>Delete</button>
                    </a>
                </div>
            </div>
            </li>
        {% endfor %}
    </ol>

apps/templates/contacts/contact_confirm_delete.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

apps/templates/contacts/contact_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>
        {% if is_update %}
            Update
        {% else %}
            Creat
        {% endif %}
            contact
    </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            {% if is_update %}
                Update
            {% else %}
                Create
            {% endif %}
        </button>
    </form>
{% endblock %}

apps/templates/contacts/contact_generate.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Contacts generate</h1>

    <form method="POST" style="margin-bottom: 1em;">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Generate</button>
    </form>

    {% include "contacts/_contact_list_base.html" with contacts_list=contacts_list %}
{% endblock %}

apps/templates/contacts/contact_generate__raw_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Contacts generate</h1>

    <form method="POST" style="margin-bottom: 1em;">
        {% csrf_token %}
        <label>
            <span>Amount</span>
            <input type="number" name="amount" value="5"/>
        </label>

        <button type="submit">Generate</button>
    </form>

    {% include "contacts/_contact_list_base.html" with contacts_list=contacts_list %}
{% endblock %}

apps/templates/contacts/contact_list.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Contacts</h1>

    {% include "contacts/_contact_list_base.html" with contacts_list=object_list %}
{% endblock %}

apps/templates/homework_11/generate_humans.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Humans</h1>
    <ol>
        {% for human in humans %}
            <li>
                <span>{{ human.name }}</span>
                <span> - </span>
                <span>{{ human.email }}</span>
                <span> : </span>
                <span>{{ human.password }}</span>
            </li>
        {% endfor %}
    </ol>
{% endblock %}